import { definePreset } from '@primeuix/themes';
import Aura from '@primeuix/themes/aura';

export const AppThemePreset = definePreset(Aura, {
  primitive: {
    borderRadius: {
      none: '0',
      xs: '2px',
      sm: 'var(--radius-sm)',
      md: 'var(--radius-md)',
      lg: 'var(--radius-lg)',
      xl: 'var(--radius-xl)',
    },
    indigo: {
      50: 'var(--primary-50)',
      100: 'var(--primary-100)',
      200: 'var(--primary-200)',
      300: 'var(--primary-300)',
      400: 'var(--primary-400)',
      500: 'var(--primary-500)',
      600: 'var(--primary-600)',
      700: 'var(--primary-700)',
      800: 'var(--primary-800)',
      900: 'var(--primary-900)',
      950: 'var(--primary-950)',
    },
    slate: {
      50: 'var(--slate-50)',
      100: 'var(--slate-100)',
      200: 'var(--slate-200)',
      300: 'var(--slate-300)',
      400: 'var(--slate-400)',
      500: 'var(--slate-500)',
      600: 'var(--slate-600)',
      700: 'var(--slate-700)',
      800: 'var(--slate-800)',
      900: 'var(--slate-900)',
      950: 'var(--slate-950)',
    },
  },
  semantic: {
    primary: {
      50: '{indigo.50}',
      100: '{indigo.100}',
      200: '{indigo.200}',
      300: '{indigo.300}',
      400: '{indigo.400}',
      500: '{indigo.500}',
      600: '{indigo.600}',
      700: '{indigo.700}',
      800: '{indigo.800}',
      900: '{indigo.900}',
      950: '{indigo.950}',
    },
    fontFamily: 'var(--font-sans)',
    formField: {
      borderRadius: '{borderRadius.sm}',
      paddingX: '0.75rem',
      paddingY: '0.5rem',
    },
    colorScheme: {
      light: {
        surface: {
          0: 'var(--bg-panel)',
          50: 'var(--bg-app)',
          100: 'var(--bg-surface)',
          200: 'var(--bg-subtle)',
          300: 'var(--border-muted)',
          400: '{slate.400}',
          500: '{slate.500}',
          600: '{slate.600}',
          700: '{slate.700}',
          800: '{slate.800}',
          900: '{slate.900}',
          950: '{slate.950}',
        },
        primary: {
          color: 'var(--brand)',
          hoverColor: 'var(--brand-hover)',
          activeColor: 'var(--primary-800)',
          contrastColor: 'var(--text-inverse)',
        },
        formField: {
          background: 'var(--bg-panel)',
          color: 'var(--text-primary)',
          borderColor: 'var(--border-default)',
          hoverBorderColor: 'var(--border-muted)',
          focusBorderColor: 'var(--brand)',
          invalidBorderColor: 'var(--danger)',
          placeholderColor: 'var(--text-ghost)',
        },
        text: {
          color: 'var(--text-primary)',
          mutedColor: 'var(--text-muted)',
          hoverMutedColor: 'var(--text-primary)',
        },
        content: {
          background: 'var(--bg-panel)',
          borderColor: 'var(--border-default)',
          color: 'var(--text-primary)',
          hoverBackground: 'var(--bg-surface)',
        },
      },
      dark: {
        surface: {
          0: 'var(--bg-panel)',
          50: 'var(--bg-app)',
          100: 'var(--bg-surface)',
          200: 'var(--bg-subtle)',
          300: 'var(--border-muted)',
          400: '{slate.400}',
          500: '{slate.500}',
          600: '{slate.600}',
          700: '{slate.700}',
          800: '{slate.800}',
          900: '{slate.900}',
          950: '{slate.950}',
        },
        primary: {
          color: 'var(--brand)',
          hoverColor: 'var(--brand-hover)',
          activeColor: 'var(--primary-300)',
          contrastColor: 'var(--slate-950)',
        },
        formField: {
          background: 'var(--bg-panel)',
          color: 'var(--text-primary)',
          borderColor: 'var(--border-default)',
          hoverBorderColor: 'var(--border-muted)',
          focusBorderColor: 'var(--brand)',
          invalidBorderColor: 'var(--danger)',
          placeholderColor: 'var(--text-ghost)',
        },
        text: {
          color: 'var(--text-primary)',
          mutedColor: 'var(--text-muted)',
          hoverMutedColor: 'var(--text-primary)',
        },
        content: {
          background: 'var(--bg-panel)',
          borderColor: 'var(--border-default)',
          color: 'var(--text-primary)',
          hoverBackground: 'var(--bg-surface)',
        },
      },
    },
  },
});
